adding more tooling and startup scripts

diff --git a/rectangles b/rectangles
--- a/rectangles
+++ b/rectangles
@@ -1,1 +1,22 @@
 #!/bin/bash
+
+error() {
+  local parent_lineno="$1"
+  local message="$2"
+  local code="${3:-1}"
+  if [[ -n "$message" ]] ; then
+    echo "Error on or near line ${parent_lineno}: ${message}; exiting with status ${code}"
+  else
+    echo "Error on or near line ${parent_lineno}; exiting with status ${code}"
+  fi
+  exit "${code}"
+}
+trap 'error ${LINENO}' ERR
+
+prev_pwd=`pwd`
+dir=$(cd -P -- "$(dirname -- "$0")" && pwd -P)
+cd $dir || exit
+./mvnw install -pl rectangles-cli -am
+cd rectangles-cli || exit
+../mvnw spring-boot:run
+cd $prev_pwd || exit
